[project]
name = "toying_with_mcp_features"
version = "0.1.0"
dependencies = [
    "fastmcp>=2.11.3",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[dependency-groups]
dev = [
    "lmstudio>=1.5.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "ruff",
]
